Fix relative import on Python 3.
And move `_`to new modules `messagefactory.py`.
This avoids an errror on startup:

```
ImportError: cannot import name '_' from partially initialized module 'cs.adminlanguage'
(most likely due to a circular import)
```